### ISSUE TITLE
Playlists support

### ISSUE THREAD

**Issue by Hiho2950** [MAJigsaw77/hxvlc#1]
is there an ability to load a youtube video using it like vlc

**Comment by MAJigsaw77** [comment]
playlist stuff isn't working for now in here, maybe in the future it will be able to.

**Comment by Hiho2950** [comment]
> playlist stuff isn't working for now in here, maybe in the future it will be able to.

i didnt mean playlist i mean loading youtube videos without playlists

**Comment by Hiho2950** [comment]
> playlist stuff is making (YouTube, Twitch, Vimeo, etc.) playback to work.

ah ok because they dont have raw like gihub

**Comment by MAJigsaw77** [comment]
The video must be on a absolute path `/storage/emulated/0/`.

**Comment by MAJigsaw77** [comment]
I'll add this to the todo list so there no point on keeping this issue open.
