### ISSUE TITLE
ios compiling error

### ISSUE THREAD

**Issue by mayo78** [MAJigsaw77/hxvlc#19]
@Futuredorito  because they did the ios stuff i think

im pretty sure did all the correct things.. using  haxe 4.2.5 and latest lime and openfl btw, not sure if that matters

<img width="868" alt="image" src="https://github.com/MAJigsaw77/hxvlc/assets/75394229/c5143368-44ac-4424-b218-6f4e80f3bd9b">

**Comment by MAJigsaw77** [comment]
Add the headers search path

**Comment by Futuredorito** [comment]
did you add the framework?

**Comment by Futuredorito** [comment]
pretty sure i figured out the issue, the headers may need to be added with the build.xml. jigsaw doesnt want me to commit it so try changing it locally

**Comment by Futuredorito** [comment]
pretty sure i figured out the issue, the headers may need to be added with the build.xml. jigsaw doesnt want me to commit it so try changing it locally

**Comment by Futuredorito** [comment]
jigsaw deleted my comment

**Comment by MAJigsaw77** [comment]
> @Futuredorito because they did the ios stuff i think
> 
> im pretty sure did all the correct things.. using haxe 4.2.5 and latest lime and openfl btw, not sure if that matters
> 
> <img alt="image" width="868" src="https://private-user-images.githubusercontent.com/75394229/300291866-c5143368-44ac-4424-b218-6f4e80f3bd9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NzcwNTQsIm5iZiI6MTcwNjQ3Njc1NCwicGF0aCI6Ii83NTM5NDIyOS8zMDAyOTE4NjYtYzUxNDMzNjgtNDRhYy00NDI0LWIyMTgtNmY0ZTgwZjNiZDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDIxMTkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYzFlMDZiMTliNWVmNDc4ZThjYjdjZTU3ZGFkOTJjZDJjNzQyNDk2YmY4NTY4YTJmNWE1ZmZiODdkZDIwODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4f179WDh_sC1WRyB9XdIo1HQdQqrIU2mxlL0-7MF_LI">

Fixed on the latest commit
