### ISSUE TITLE
idk what title should be used

### ISSUE THREAD

**Issue by Hiho2950** [MAJigsaw77/hxvlc#2]
the game crashes without giving an error message or a crash handler on the part when "var video = new FlxVideo()"
on android arm64

**Comment by MAJigsaw77** [comment]
Look on the [`flixel`](samples/flixel) sample to understand how it works.

**Comment by Hiho2950** [comment]
> Look on the [`flixel`](samples/flixel) sample to understand how it works.

it s the same what i had do

**Comment by Hiho2950** [comment]
i will try to rebuild without using cache cuz it had a cache from hxCodec

**Comment by Hiho2950** [comment]
> i will try to rebuild without using cache cuz it had a cache from hxCodec

i didnt work and still auto close
