### ISSUE TITLE
video crashes when using bytes instead of path

### ISSUE THREAD

**Issue by mayo78** [MAJigsaw77/hxvlc#20]
saw this happen on both ios and mac, i was able to fix this by not doing [this](https://github.com/MAJigsaw77/hxvlc/blob/main/source/hxvlc/openfl/Video.hx#L520-L524) bit of code when bytes were used but i dont really know how this stuff works so im sure theres a better way

**Comment by MAJigsaw77** [comment]
That variables are meant for freeing memory

**Comment by MAJigsaw77** [comment]
What are you trying to do?

**Comment by MAJigsaw77** [comment]
You should show your code though

**Comment by MAJigsaw77** [comment]
Try the latest commit and see what happens
