### ISSUE TITLE
[Flixel] Volume doesn't follow application volume

### ISSUE THREAD

**Issue by ActualMandM** [MAJigsaw77/hxvlc#25]
When a video is playing, adjusting it in volume mixer will have the video volume adjust for a split second before going back to Flixel's set volume.

https://github.com/MAJigsaw77/hxvlc/assets/15317421/037bc916-5cef-4214-ace9-cd3a8f408536

**Comment by MAJigsaw77** [comment]
As you can see, on the flixel backend we are automatically handling the volume according to [flixel's sound global volume](https://github.com/MAJigsaw77/hxvlc/blob/1557c1ec2d29a2fb0c2933d51efeab71cfe59ac0/source/hxvlc/flixel/FlxVideo.hx#L89).

**Comment by MAJigsaw77** [comment]
But you can prevent that by setting `autoVolumeHandle` to `false`.

**Comment by MAJigsaw77** [comment]
Maybe there might be a issue with the `mute` variable.

**Comment by MAJigsaw77** [comment]
Try the latest commit on the repo and see if it works now.

**Comment by MAJigsaw77** [comment]
> Try the latest commit on the repo and see if it works now.

It's kinda odd to me tbh, i never seen something like this before.

**Comment by MAJigsaw77** [comment]
Ok so, after doing some research, this issue might actually be impossible to fix as we are constantly setting the volume of the libvlc media player to the flixel sound global volume.

**Comment by MAJigsaw77** [comment]
> Ok so, after doing some research, this issue might actually be impossible to fix as we are constantly setting the volume of the libvlc media player to the flixel sound global volume.

Apparently it might be related to this issue https://forum.videolan.org/viewtopic.php?t=142860

**Comment by MAJigsaw77** [comment]
https://github.com/MAJigsaw77/hxvlc/commit/7e1f85bcb9271d686588572ee98d6c777d58b8cb

**Comment by MAJigsaw77** [comment]
This ended up fixing this issue.
