### ISSUE TITLE
Way to seek/loop ?

### ISSUE THREAD

**Issue by f-rank** [MAJigsaw77/hxvlc#51]
Hi, banger project..

Just asking if there's a way to seek or loop the video. Probably there is but it is escaping me.

**Comment by MAJigsaw77** [comment]
You can use the `position/time` variable to seek the video, about looping, you can use `video.load('assets/video.mp4', [':input-repeat=65535']);` this.

**Comment by f-rank** [comment]
Thanks, I was wrongly looking for  "seek" or something like it and missed those.
