### ISSUE TITLE
Issue with compiling

### ISSUE THREAD

**Issue by Zuk0109** [MAJigsaw77/hxvlc#63]
ive been trying to compile for like a week straight and before this error i was getting a video.cpp error. i fixed that by changing my hxcodec version to 2.6.0 but now when i compile or open the exe i get a new error:

![image](https://github.com/user-attachments/assets/c81a6abe-2247-473d-b0ee-addc8c0a291d)

Note: my friend @boohglas DID use hxvlc to make a intro cutscene, and it compiled and worked for him, but it wont for me. am i missing something here?

**Comment by MAJigsaw77** [comment]
Remove the export folder and hxcodec library from the project and then it should work fine.

**Comment by Zuk0109** [comment]
source/states/PlayState.hx:44: characters 14-28 : Type not found : vlc.MP4Handler
source/states/PlayState.hx:847: characters 13-25 : Type not found : VideoHandler

new error

**Comment by MAJigsaw77** [comment]
That's not from within hxvlc

**Comment by Zuk0109** [comment]
i looked it up and it has to do with me removing hxcodec

**Comment by Zuk0109** [comment]
im still confused as to what to do cause once i removed hxcodec and deleted the export like you said and the compiled, compilation started fighting for its life cause i removed hxcodec. do i change anything in playstate.hx?

**Comment by MAJigsaw77** [comment]
> im still confused as to what to do cause once i removed hxcodec and deleted the export like you said and the compiled, compilation started fighting for its life cause i removed hxcodec. do i change anything in playstate.hx?

Yes, hxcodec and hxvlc aren't the same libraries

**Comment by Zuk0109** [comment]
well i know that much. what else do i change though
