### ISSUE TITLE
Destroying an FlxVideoSprite freezes the game.

### ISSUE THREAD

**Issue by sillycodergirl** [MAJigsaw77/hxvlc#69]
Greetings, I was working on a project and was notified that a video was crashing/freezing (not responding) the game after being played and `video.destroy();` was called upon it.

After debugging, I determined that a possible root cause was with destroying said VideoSprite.
Here is a Pesudo-Stack:
```
LibVLC.media_player_stop <-- error is here
Video.dispose()
FlxVideoSprite.destroy()
```

I have tried to look for the true root cause but unable as I am not too familiar with C++ (I am assuming)

Thank you for reading this, good day :).

**Comment by MAJigsaw77** [comment]
Show the way you play the video

**Comment by sillycodergirl** [comment]
This is the code:

```haxe
var video:FlxVideoSprite = new FlxVideoSprite(0, 0);

video.bitmap.onFormatSetup.add(function()
{
	video.setGraphicSize(FlxG.width, FlxG.height);
	video.updateHitbox();
	video.screenCenter();
});

video.bitmap.onEndReached.add(function()
{
	//startIntro();
	video.destroy();
});

video.antialiasing = true;
video.load(Paths.video('haxe'));
add(video);
video.play();
```

**Comment by MAJigsaw77** [comment]
Are you using the latest?
